name: Build and Test LibGDX Project

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main", "feature/*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build      
        
      - name: Run tests
        run: ./gradlew test
        
      # - name: Upload Test Results
      #   if: always()
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: test-results
      #     path: |
      #       **/build/reports/tests/
      #       **/build/test-results/
            
      # - name: Build JAR
      #   run: ./gradlew lwjgl3:jar
        
      # - name: Upload JAR artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: game-jar
      #     path: lwjgl3/build/libs/OneGame-1.0.0.jar